version: "3.8"
services:
  db:
    image: postgres:17-bookworm
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
    networks:
      - vetone_back

  redis:
    restart: unless-stopped
    image: redis:7.4.0-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - "6379"
    environment:
      - TZ=Asia/Tehran
    networks:
      - vetone_back

  web:
    build: .
    command: >
      sh -c "python manage.py migrate --no-input &&
       python manage.py collectstatic --no-input &&
       gunicorn --bind 0.0.0.0:8000 --forwarded-allow-ips='*' --access-logfile - --workers 3 --timeout 120 config.wsgi:application"
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DEBUG=False
      - TZ=Asia/Tehran
    networks:
      - vetone_back

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    env_file:
      - .env
    environment:
      - DEBUG=False
      - TZ=Asia/Tehran
    networks:
      - vetone_back

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - celery_worker
    env_file:
      - .env
    environment:
      - DEBUG=False
      - TZ=Asia/Tehran
    restart: unless-stopped
    networks:
      - vetone_back
  
  flower:
    build: .
    command: celery -A config flower --port=5555 --basic_auth="vetone:vetone" 
    ports:
      - 5555:5555
    depends_on:
      - celery_worker
    env_file:
      - .env
    environment:
      - DEBUG=False
      - TZ=Asia/Tehran
    restart: unless-stopped
    networks:
      - vetone_back

networks:
  vetone_back:
